### ISSUE TITLE
Error Running BugBase with WGS data from Shogun

### ISSUE THREAD

**Issue by cmstaley** [knights-lab/BugBase#1]
I have bugbase installed (example inputs work correctly for 16S data) and have finished the Shogun pipeline for WGS data. 

I get the following error using my data:
run.bugbase.r -i ./taxa_counts.txt -m ./byron_mapping.txt -c Arm -w -o ./results
Loading required package: methods
[1] "Loading Inputs..."
[1] "WGS specified, no copy number normalization will take place..."
[1] "Predicting phenotypes..."
Error in single.cell.predictions(trait_table, loaded.inputs$otu_table,  : 
  Error: no OTU overlap between OTU table and trait table.
Execution halted

The files I'm trying to use are attached. Do I need to write a separate trait table (how?) or is there a BugBase default for this? or some other fix? 
[byron_mapping.txt](https://github.com/knights-lab/BugBase/files/622631/byron_mapping.txt)
[taxa_counts.txt](https://github.com/knights-lab/BugBase/files/622632/taxa_counts.txt)

Thanks

**Comment by TonyaWard** [comment]
Hi!

Is there a way you can give us your files so we can try and pick OTUs for you?  I think it’s a problem with the shogun pipeline.  The BugBase error is that none of the OTU IDs match between your OTU table and all the OTU IDs we use for shotgun data.

Your files would be super helpful to generate/troubleshot the OTU table generation.

-Tonya

**Comment by cmstaley** [comment]
No problem! All of the raw data and intermediate files should be available to you in /scratch/staleyc/byron/ssg/

**Comment by bhillmann** [comment]
Everything looks good for intermediates. Only question, where is the ```path_to_shogun_bugbase_db``` for the command:

```
# run OTU picking with shogun
shogun_bugbase -i path_to_sequences -o output_path -u path_to_shogun_bugbase_db
```

**Comment by cmstaley** [comment]
That command was
shogun_bugbase -i /panfs/roc/scratch/staleyc/byron/ssg/ -o /panfs/roc/scratch/staleyc/byron/ssg/shogun/ -u /home/sadowsky/staleyc/shogun_bugbase_db

In [/home/sadowsky/staleyc/shogun_bugbase_db/] I have (md5sum):
ed38b3b29c40af4200e21d46624c18f7  img.genes.ctr
d15b77d77b99bc2da06e5a17896ac9b8  img_map.pkl

**Comment by bhillmann** [comment]
For some reason the ```img_map.pkl``` is wrong. Can you replace it with this one and try again? All you have to do is delete the file:

```
/scratch/staleyc/byron/ssg/shogun/taxa_counts.txt
```

And then update the folder:

```
/home/sadowsky/staleyc/shogun_bugbase_db/img_map.pkl
```

With the map attached here (after unzipping it of course).
[img_map.zip](https://github.com/knights-lab/BugBase/files/622894/img_map.zip)

**Comment by tonyaward4** [comment]
Despite these updates there is still an underlying issue of no OTUs overlapping. I will try and resolve this for you!

Thanks for being patient!

**Comment by tonyaward4** [comment]
The BugBase WGS tables and shogun_bugbase_db map have been updated and should now run properly (at least when I tried with your data!).  

**Please try the following and let us know if it works for you**:

1. Update the map file in your shogun_bugbase_db directory (/home/sadowsky/staleyc/shogun_bugbase_db). The updated version is here: 
[https://drive.google.com/drive/folders/0BxxDnVKH5iPuOTVyM3N2U0JpNXM]

2. Re-download the latest BugBase version (delete your current version and replace with a new download)

3. Re-pick OTUs with shogun

4. Use BugBase for your predictions with the -w option for WGS

**Comment by tonyaward4** [comment]
The BugBase WGS tables and shogun_bugbase_db map have been updated and should now run properly (at least when I tried with your data!).

**Please try the following and let us know if it works for you:**

1. Update the map file in your shogun_bugbase_db directory (/home/sadowsky/staleyc/shogun_bugbase_db). The updated version is here:
https://drive.google.com/drive/folders/0BxxDnVKH5iPuOTVyM3N2U0JpNXM

2. Re-download the latest BugBase version (delete your current version and replace with a new download)

3. Re-pick OTUs with shogun

4. Use BugBase for your predictions with the -w option for WGS

**Comment by cmstaley** [comment]
I think there might be a problem with the shogun database. When I download and try to extract I get the warning

Archive:  shogun_bugbase_db.zip
warning [shogun_bugbase_db.zip]:  4294967296 extra bytes at beginning or within zipfile

After extracting anyway and trying to call OTUs I get:

Using 32-bit counters
16777217 elements read.
Nodes in input tree: 1291330052 (PACKSIZE=32, CNTTYPE=NA, IXTYPE=uint16_t, SZ=7)
Error in reading tree.

**Comment by TonyaWard** [comment]
We have updated the database files, and have added their md5 checksums.

You can find those files here:
https://drive.google.com/open?id=0ByVmiknyDGaiM3M0dDBJMkZuZDg

Can you please download and try these?

**Comment by cmstaley** [comment]
Thanks, Tonya! I just finished working with it and I have data now.

**Comment by TonyaWard** [comment]
That's great! Thanks for using BugBase!
