### ISSUE TITLE
Bug if OTUs are not numeric

### ISSUE THREAD

**Issue by michoug** [knights-lab/BugBase#2]
Hi,

If inside the OTU table, the otus id are not numeric  the software gives this error

```
[1] "Loading Inputs..."

Either 'predict only' or 'plot all' specified. All samples will be predicted.
[1] "16S copy number normalizing OTU table..."
[1] "Predicting phenotypes..."
Error in single.cell.predictions(trait_table, normalized_otus, test_trait,  : 
  Error: no OTU overlap between OTU table and trait table.
Execution halted

```
Best
Greg

**Comment by michoug** [comment]
Hi,
Sorry I realized that the otus should be named based on the greengenes database, whereas the number I got from mine were "random" as OTU_1, OTU_2...
Any ideas how to resolve this issue, to base the comparison with the greengenes database not on the number but on the taxonomy (e.g k__Bacteria; p__Bacteroidetes; c__Flavobacteriia)
Best
Greg

**Comment by TonyaWard** [comment]
Hi Greg,
At this time, BugBase can only use the GreenGenes OTU ID (16S) or the IMG OTU ID (Shotgun) to output predictions. If you'd like to use BugBase to predict phenotypes you'll have to use an OTU picker with the GreenGenes (16S) or IMG database (shotgun) using a closed reference approach. 
Thanks for using BugBase!
